services:
  web:
    container_name: my_app_name
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
